'use client';

import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Next.js Secure Login',
//   description: 'Generated by Secure Login next app',
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-r from-gray-900 via-gray-800 to-gray-900 text-white flex flex-col min-h-screen`}
      >
        <header className="w-full bg-gray-800 p-4 shadow-md z-10">
          <nav className="max-w-7xl mx-auto flex justify-between items-center">
            <ul className="flex space-x-4">
              <li>
                <Link href="/" className="hover:text-blue-400">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/register" className="hover:text-blue-400">
                  Register
                </Link>
              </li>
              <li>
                <Link href="/login" className="hover:text-blue-400">
                  Login
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="flex-1 flex items-center justify-center p-4">
          <SessionProvider>{children}</SessionProvider>
        </main>
        <footer className="w-full bg-gray-800 p-4 shadow-md z-10">
          <p className="text-center">Footer content</p>
        </footer>
      </body>
    </html>
  );
}
